### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by bamueh** [VirologyCharite/ConsensusDeduplication#1]
Hi, I tried to run `$ .sort_reads.py --h` and I'm getting the following error:

```
$ .sort_reads.py --h
  File ".sort_reads.py", line 102
    with (pysam.AlignmentFile(samfile_name, "r") as samfile,):
                                                  ^
SyntaxError: invalid syntax
```

Fixing that, I then get 
```
$ .sort_reads.py -h
Traceback (most recent call last):
  File ".sort_reads.py", line 13, in <module>
    from filter_spurious_reads import filter_spurious_reads
  File "ConsensusDeduplication/filter_spurious_reads.py", line 14, in <module>
    ) -> list[list[list[pysam.AlignedSegment]]]:
TypeError: 'type' object is not subscriptable
```

**Comment by terrycojones** [comment]
Why the `.` before `sort_reads.py` ?

What's your Python version? @imLew is using `list[...]` as a type hint, and I think `list` only supported that in quite recent Python versions.

**Comment by bamueh** [comment]
Yeah OK, I was using Python 3.7. All those errors came from that.
