### ISSUE TITLE
Maximum recursion depth

### ISSUE THREAD

**Issue by bamueh** [VirologyCharite/ConsensusDeduplication#2]
More of an FYI than a bug:

```
$ ./../../../../../ConsensusDeduplication/sort_reads.py D_240322_11_10508_1_rna-caplib-240227-97_RNA_S9_R1_001.bam reference.fasta -t CoDe
Traceback (most recent call last):
  File "/Users/barbara/dark-matter/mers/data/raw/240322_MERS_NHMBat_Phlebovirus_Caplib_MiniSeq-hcov/D_240322_11_10508_1_rna-caplib-240227-97_RNA/./../../../../../ConsensusDeduplication/sort_reads.py", line 250, in <module>
    main()
  File "/Users/barbara/dark-matter/mers/data/raw/240322_MERS_NHMBat_Phlebovirus_Caplib_MiniSeq-hcov/D_240322_11_10508_1_rna-caplib-240227-97_RNA/./../../../../../ConsensusDeduplication/sort_reads.py", line 215, in main
    filtered_list, unfiltered_list = deduplicate_samfile(
  File "/Users/barbara/dark-matter/mers/data/raw/240322_MERS_NHMBat_Phlebovirus_Caplib_MiniSeq-hcov/D_240322_11_10508_1_rna-caplib-240227-97_RNA/./../../../../../ConsensusDeduplication/sort_reads.py", line 110, in deduplicate_samfile
    filtered_reads_list = filter_spurious_reads(
  File "/Users/barbara/dark-matter/ConsensusDeduplication/filter_spurious_reads.py", line 72, in filter_spurious_reads
    cluster_list = cluster_reads(filtered_reads_dict, cluster_size)
  File "/Users/barbara/dark-matter/ConsensusDeduplication/filter_spurious_reads.py", line 41, in cluster_reads
    cluster_list.extend(cluster_reads(reads_dict, cluster_size))
  File "/Users/barbara/dark-matter/ConsensusDeduplication/filter_spurious_reads.py", line 41, in cluster_reads
    cluster_list.extend(cluster_reads(reads_dict, cluster_size))
  File "/Users/barbara/dark-matter/ConsensusDeduplication/filter_spurious_reads.py", line 41, in cluster_reads
    cluster_list.extend(cluster_reads(reads_dict, cluster_size))
  [Previous line repeated 990 more times]
  File "/Users/barbara/dark-matter/ConsensusDeduplication/filter_spurious_reads.py", line 28, in cluster_reads
    distances = np.abs(np.sum(X, axis=2))
  File "/Users/barbara/opt/anaconda3/envs/310pip/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2313, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/Users/barbara/opt/anaconda3/envs/310pip/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 72, in _wrapreduction
    passkwargs = {k: v for k, v in kwargs.items()
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I guess there are too many reads.

**Comment by terrycojones** [comment]
This looks 100% like a bug to me! The function is calling itself with the exact same arguments, which would go on forever, but Python runs out of room for the new stack frames and gives up.

**Comment by bamueh** [comment]
FYI, when I use a smaller bam file (`D_240322_12_10509_1_rna-caplib-240227-98_RNA`) the code works fine. So I guess it has something to do with the number of reads.

**Comment by imLew** [comment]
Thanks for verifying that.

If you want to just use it now for the bigger file as well you can add
```
import sys
sys.setrecursionlimit(10**6)
```
to the top of the filter_spurious_reads.py file

**Comment by bamueh** [comment]
OK, that works. Can I make a pr that just hardcodes that change?
